# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-tests-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Testes da API REST myCoins collections mycoins
        run: newman run https://www.getpostman.com/collections/b25bf2beeafb2415253c -e myCoins.environment.json -d coinScenarios.json -r htmlextra --reporter-htmlextra-export reports/newman/html/test_my_coins.html

      - name: Testes da API REST myCoins collections searchCoinsWithFilter
        run: newman run https://www.getpostman.com/collections/bee61346a6a4d37fd282 -e myCoins.environment.json -d coinScenarios.json -r htmlextra --reporter-htmlextra-export reports/newman/html/test_search_coins_with_filter.html

      - name: Testes da API REST myCoins collections userMyCoinsLogin
        run: newman run https://www.getpostman.com/collections/c73d28b97ee6ebc9a424 -e myCoins.environment.json -d coinScenarios.json -r htmlextra --reporter-htmlextra-export reports/newman/html/test_user_my_coins_login.html

  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_PROJECT_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          checkstring: 'ok'